---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  product_name: chef
  product_version: latest
  channel: stable
  install_strategy: once
  always_update_cookbooks: true
  log_level: info

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools sudo

suites:
  - name: default
    driver:
      hostname: java
    run_list:
      - recipe[java-chef::install]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      java:
        install_from: 'oracle_source'
        install_version: 'jdk-8u181-linux-x64'
