---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: latest
  channel: stable
  install_strategy: once
  always_update_cookbooks: true
  #log_level: info

verifier:
  name: inspec

platforms:
  - name: centos-7.4

suites:
  - name: default
    driver:
      vm_hostname: java
      customize:
        memory: 512
        cpus: 1
        natdnshostresolver1: "on"
    run_list:
      - recipe[java-chef::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      java:
        install_from: 'oracle_source'
        install_version: 'jdk-8u172-linux-x64'
