---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 14
  channel: stable
  install_strategy: once
  always_update_cookbooks: true
  log_level: info
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: centos-7.6

suites:
  - name: default
    driver:
      vm_hostname: java
      customize:
        memory: 512
        cpus: 1
        natdnshostresolver1: "on"
    run_list:
      - recipe[java-chef::install]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      java:
        install_from: 'amazon_source'
        install_version: 'jdk-8u212-linux-x64'
