---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 13.1.31

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    driver:
      vm_hostname: java
      customize:
        memory: 512
        cpus: 1
        natdnshostresolver1: "on"
    run_list:
      - recipe[java-chef::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
