name 'java-chef'
maintainer 'Ryan Hansohn'
maintainer_email 'info@imnorobot.com'
license 'MIT'
description 'Installs/Configures java-chef'
version '2.2.0'
chef_version '>= 12.1'
source_url 'https://github.com/hansohn/java-chef'
issues_url 'https://github.com/hansohn/java-chef/issues'

supports 'centos', '>= 7.0'
